services:
  backend:
    build: ./backend
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - TEMPLATE_DIR=/app/templates
      - AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
    volumes:
      - ./backend/app:/app/app
      - cv_templates:/app/templates
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"

  frontend:
    image: node:20-alpine
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_AUTH0_DOMAIN=${VITE_AUTH0_DOMAIN}
      - VITE_AUTH0_CLIENT_ID=${VITE_AUTH0_CLIENT_ID}
      - VITE_AUTH0_AUDIENCE=${VITE_AUTH0_AUDIENCE}
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    command: sh -c "npm ci || npm i && npm run dev -- --host"
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  cv_templates:
  frontend_node_modules:
